<a href="https://colab.research.google.com/github/Khaled-Mohammed-Abdelgaber/PPG_Clustering/blob/main/LDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [3]:
import pandas as pd 
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [6]:
ppg_one_beat = pd.read_csv("/content/gdrive/MyDrive/data/peak2peak_aug_2022/Part_1/p2p_beats/part_1_PPG_beats_P2P_Aug_2022.csv",
                           names = np.arange(120))
ppg_10_beats = pd.read_csv("/content/gdrive/MyDrive/data/peak2peak_aug_2022/Part_1/10_beat_signals/part_1_PPG_signals_10_beats_Aug_2022.csv",
                           names = np.arange(1024))
id = pd.read_csv("/content/gdrive/MyDrive/data/peak2peak_aug_2022/Part_1/p2p_beats/part_1_Subj_ID_beats_P2P_Aug_2022.csv",names = ["ID"])
sys_df = pd.read_csv("/content/gdrive/MyDrive/data/peak2peak_aug_2022/Part_1/p2p_beats/part_1_SYS_BP_beats_P2P_Aug_2022.csv",
                     names = ["sys"])
dia_df = pd.read_csv("/content/gdrive/MyDrive/data/peak2peak_aug_2022/Part_1/p2p_beats/part_1_Dia_BP_beats_P2P_Aug_2022.csv",
                     names = ["dia"])

In [7]:
df_info = pd.DataFrame()
 
df_info["dia"]  = dia_df
df_info["sys"]  = sys_df
df_info["ID"] = id

In [8]:
X = ppg_one_beat.values

In [14]:
y = df_info["sys"].values

In [15]:
type(y)

numpy.ndarray

In [16]:
for i in range(len(y)):
  if y[i] < 80:
    y[i] = 0
  elif y[i] < 90:
    y[i] = 1
  elif y[i] < 100:
    y[i] = 2
  elif y[i] < 110:
    y[i] = 3
  elif y[i] < 120:
    y[i] = 4 
  elif y[i] < 130:
    y[i] = 5
  elif y[i] < 140:
    y[i] = 6
  elif y[i] < 150:
    y[i] = 7
  elif y[i] < 160:
    y[i] = 8
  elif y[i] < 170:
    y[i] = 9
  elif y[i] < 180:
    y[i] = 10
  elif y[i] < 190:
    y[i] = 11
  else:
    y[i] = 12


In [17]:
y

array([5., 5., 4., ..., 1., 1., 1.])

In [24]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
colors = ['royalblue','red','deeppink', 'maroon', 'mediumorchid', 'tan', 'forestgreen', 'olive', 'goldenrod', 'lightcyan', 'navy']
vectorizer = np.vectorize(lambda x: colors[x % len(colors)])

In [22]:
lda = LinearDiscriminantAnalysis(n_components=12)
X_lda_comp = lda.fit(X, y).transform(X)

In [23]:
lda.explained_variance_ratio_

array([0.51752546, 0.16698827, 0.1229704 , 0.06028748, 0.05000757,
       0.02965918, 0.01789165, 0.01304061, 0.00952329, 0.00719488,
       0.00278347, 0.00212774])

In [26]:
X_lda_comp.shape

(154540, 12)

In [41]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
import matplotlib.pyplot as plt


 
# initialise kmeans
kmeans = KMeans(n_clusters=12)
kmeans.fit(X_lda_comp)
cluster_labels = kmeans.labels_

In [43]:
cluster_labels

array([11, 11, 11, ...,  6,  6,  6], dtype=int32)

In [ ]:
for i in range(12):
  plt.figure(i);
  plt.plot(ppg_one_beat[cluster_labels == i].values[:].T,alpha = 0.5);

In [ ]:
ppg_one_beat[cluster_labels == 0].values[:].shape